language: python
sudo: "required"
services:
  - docker
env:
  matrix:
    - OS=centos
      OS_VERSION=7
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=29
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=30
      PYTHON_VERSION=3
install:
 - pip install coveralls
script:
 - ./test.sh
after_success: coveralls
notifications:
  email: false
